export type UnitOption = {
  value: string;
  label: string;
};

export const UNIT_OPTIONS: readonly UnitOption[] = [
  { value: '', label: 'Ohne Einheit' },
  { value: 'mg', label: 'Milligramm (mg)' },
  { value: 'g', label: 'Gramm (g)' },
  { value: 'kg', label: 'Kilogramm (kg)' },
  { value: 'ml', label: 'Milliliter (ml)' },
  { value: 'cl', label: 'Zentiliter (cl)' },
  { value: 'dl', label: 'Deziliter (dl)' },
  { value: 'l', label: 'Liter (l)' },
  { value: 'TL', label: 'Teelöffel (TL)' },
  { value: 'EL', label: 'Esslöffel (EL)' },
  { value: 'Stück', label: 'Stück' },
  { value: 'Prise', label: 'Prise' },
  { value: 'Zehe', label: 'Zehe' },
  { value: 'Bund', label: 'Bund' },
  { value: 'Scheibe', label: 'Scheibe' },
  { value: 'Blatt', label: 'Blatt' },
  { value: 'Tasse', label: 'Tasse' },
  { value: 'Dose', label: 'Dose' },
  { value: 'Pck', label: 'Packung (Pck)' },
  { value: 'Flasche', label: 'Flasche' },
  { value: 'Tüte', label: 'Tüte' },
  { value: 'Glas', label: 'Glas' },
] as const;

const UNIT_ALIASES: Record<string, string> = {
  g: 'g',
  gramm: 'g',
  gr: 'g',
  kg: 'kg',
  kilogramm: 'kg',
  kilo: 'kg',
  mg: 'mg',
  milligramm: 'mg',
  ml: 'ml',
  milliliter: 'ml',
  l: 'l',
  liter: 'l',
  ltr: 'l',
  cl: 'cl',
  centiliter: 'cl',
  zentiliter: 'cl',
  dl: 'dl',
  deziliter: 'dl',
  tl: 'TL',
  'teelöffel': 'TL',
  tsp: 'TL',
  el: 'EL',
  'esslöffel': 'EL',
  tbsp: 'EL',
  'stück': 'Stück',
  stueck: 'Stück',
  stk: 'Stück',
  'stk.': 'Stück',
  x: 'Stück',
  zehe: 'Zehe',
  zehen: 'Zehe',
  bund: 'Bund',
  scheibe: 'Scheibe',
  scheiben: 'Scheibe',
  blatt: 'Blatt',
  'blätter': 'Blatt',
  prise: 'Prise',
  prisen: 'Prise',
  tasse: 'Tasse',
  tassen: 'Tasse',
  dose: 'Dose',
  dosen: 'Dose',
  pck: 'Pck',
  'pck.': 'Pck',
  packung: 'Pck',
  packungen: 'Pck',
  flasche: 'Flasche',
  flaschen: 'Flasche',
  'tüte': 'Tüte',
  tuete: 'Tüte',
  tueten: 'Tüte',
  'tüten': 'Tüte',
  glas: 'Glas',
  'gläser': 'Glas',
};

export function normalizeUnit(value?: string | null) {
  const raw = value?.trim() || '';
  return UNIT_ALIASES[raw.toLowerCase()] || raw;
}
